### PR TITLE
Monitoring

### PR DESCRIPTION
**Pull request by ebiiii**
Adding support for gathering metrics about GSN internals. A class can be "Monitorable" if it can report some statistics. Those statistics are meant to be collected by an external process through the web interface (for example a munin plugin is provided).
All Monitorable classes have to be registered in the Main class. 
The output format of the web interface consists of two lines, the first one has the names of the fields* separated by "," and the second line has the values with the same separators.

*the names follow this convention: [vs name]:[input source name]:[metric name]:[type]
where [vs name], the virtual sensor name and  [input source name] are taken from the xml configuration file and can be omitted if the statistics is related to the virtual sensor itself (no need for the input source name) or the whole GSN server (no need for both of them).
The metric name has to be unique within its scope (the two previous names).
The type can be "count" or "value", count means it is a counter and the derivative is the interesting metric, whereas value means the value itself is to be showed. (this is a bit different than the type values in munin)

### CODE REVIEW

**Comment by jpcik** [comment]
1st question, why adding _wrapper? to initialize, dispose, dataavailable?

**Comment by jpcik** [comment]
If a virtual sensor overrrides the getStatistics, the default ones will be lost?

**Comment by ebiiii** [comment]
for the 1st question, I need to have the "monitoring function" called every time one of those is called. But if I let it to the user that will be extending those classes, it will duplicate a lot of code and they may forget to do it. I changed the name of the callback function, but not the one that is implemented in new wrappers/vs, so that it is retro-compatible. The suffix "\_wrapper" is maybe badly chosen as _wrapper_ has another meaning in GSN...  The idea behind is similar to the decorators in python, but I'm not sure what is the actual equivalent in java.

Yes, I should also have used the same "_wrapper" trick there, to the getStatistics method.

**Comment by jpcik** [comment]
for the servlet service, would it make sense to use json as output? the current format is some sort of CSV right?. I have doubts about this type of formatting.

**Comment by ebiiii** [comment]
Yes, the choice of the output format is probably not optimal. 
But looking at what kind of input is expected by monitoring software, it doesn't seem to have any kind of agreement out there. 
I just found that : http://metrics20.org/spec/ 
It looks like json and would be verbose enough to describe precisely the various metrics we could find in GSN... 
Anyway for the monitoring tools (munin, nagios,...) there will always be some script to translate between the formats.

**Comment by jpcik** [comment]
I see. maybe i was too optimistic to think that this was somehow 'standardized'.

**Comment by ebiiii** [comment]
Another option is to use the graphite/carbon syntax: http://graphite.readthedocs.org/en/latest/feeding-carbon.html#getting-your-data-into-graphite and http://matt.aimonetti.net/posts/2013/06/26/practical-guide-to-graphite-monitoring/ 
each line is a metric in the form : <metric name> <metric value> <timestamp>
and the name uses a dot convention for defining how it should be aggregated and visualized.

**Comment by ebiiii** [comment]
Regarding the overriding of getStatistics, I'm not sure how to do it properly. The interface Monitorable says that there should be a getStatistics method that is use to aggregate statistics about each registered classes. All the wrappers and virtual sensors are automatically by default monitored. If someone wants to have some other output from a specific wrapper (for example counting the number of errors of a parser in a wrapper), it should be able to just implement the same getStatistics method as if it was writing a simple Monitorable class (such as the MemoryMonitor one). Having a different name for the method could disturb the user... but also forcing him to call the super-class method is a bit tricky.

**Comment by ebiiii** [comment]
I renamed the *_wrapper methods to *_decorated to avoid the confusion with the notion of Wrapper in GSN. I updated the output format to something similar to what Graphite takes as input. 
And for the possibility to override getStatistics, well... I'll let it like that. It could allow the users to have non-monitored virtual sensors if needed.
If there is no other questions, we can merge this one.

**Pull request merged**
